services:
  - type: web
    name: scholchat-front
    env: node
    startCommand: node server.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production